# SPDX-FileCopyrightText: 2025 MiromindAI
#
# SPDX-License-Identifier: Apache-2.0

from ._convert_weights import qwen3_hf_to_tune, qwen3_tune_to_hf
from ._model_builders import (
    lora_qwen3_0_6b_base,
    lora_qwen3_0_6b_instruct,
    lora_qwen3_14b_base,
    lora_qwen3_14b_instruct,
    lora_qwen3_1_7b_base,
    lora_qwen3_1_7b_instruct,
    lora_qwen3_32b,
    lora_qwen3_4b_base,
    lora_qwen3_4b_instruct,
    lora_qwen3_8b_base,
    lora_qwen3_8b_instruct,
    qwen3_0_6b_base,
    qwen3_0_6b_instruct,
    qwen3_14b_base,
    qwen3_14b_instruct,
    qwen3_1_7b_base,
    qwen3_1_7b_instruct,
    qwen3_32b,
    qwen3_4b_base,
    qwen3_4b_instruct,
    qwen3_8b_base,
    qwen3_8b_instruct,
    qwen3_tokenizer,
    qwen3_tokenizer_auto,
)
from ._model_builders_yarn import (
    qwen3_0_6b_base_yarn,
    qwen3_0_6b_instruct_yarn,
    qwen3_14b_base_yarn,
    qwen3_14b_instruct_yarn,
    qwen3_1_7b_base_yarn,
    qwen3_1_7b_instruct_yarn,
    qwen3_32b_yarn,
    qwen3_4b_base_yarn,
    qwen3_4b_instruct_yarn,
    qwen3_8b_base_yarn,
    qwen3_8b_instruct_yarn,
)
from ._positional_embeddings import Qwen3YarnRotaryPositionalEmbedding
from ._tokenizer import Qwen3Tokenizer
from ._tokenizer_auto import Qwen3TokenizerAuto


__all__ = [
    "qwen3_hf_to_tune",
    "qwen3_tune_to_hf",
    "lora_qwen3_0_6b_base",
    "lora_qwen3_0_6b_instruct",
    "lora_qwen3_1_7b_base",
    "lora_qwen3_1_7b_instruct",
    "lora_qwen3_4b_base",
    "lora_qwen3_4b_instruct",
    "lora_qwen3_8b_base",
    "lora_qwen3_8b_instruct",
    "lora_qwen3_14b_base",
    "lora_qwen3_14b_instruct",
    "lora_qwen3_32b",
    "qwen3_0_6b_base",
    "qwen3_0_6b_instruct",
    "qwen3_1_7b_base",
    "qwen3_1_7b_instruct",
    "qwen3_4b_base",
    "qwen3_4b_instruct",
    "qwen3_8b_base",
    "qwen3_8b_instruct",
    "qwen3_14b_base",
    "qwen3_14b_instruct",
    "qwen3_32b",
    "qwen3_tokenizer",
    "qwen3_tokenizer_auto",
    "qwen3_0_6b_base_yarn",
    "qwen3_0_6b_instruct_yarn",
    "qwen3_1_7b_base_yarn",
    "qwen3_1_7b_instruct_yarn",
    "qwen3_4b_base_yarn",
    "qwen3_4b_instruct_yarn",
    "qwen3_8b_base_yarn",
    "qwen3_8b_instruct_yarn",
    "qwen3_14b_base_yarn",
    "qwen3_14b_instruct_yarn",
    "qwen3_32b_yarn",
    "Qwen3YarnRotaryPositionalEmbedding",
    "Qwen3Tokenizer",
    "Qwen3TokenizerAuto",
]
